spring:
  application:
    name:
      AI-Trip-Assistant
  ai:
    openai:
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: qwen-max-latest
          temperature: 0.6
      embedding:
        api-key: ${OPENAI_API_KEY}
        options:
          model: text-embedding-v3
          dimensions: 1024
    vectorstore:
      elasticsearch:
        initialize-schema: true  #springAI启动时自动会创建索引
        dimensions: 1024      # 向量维度(模型必须能支持)
        index-name: trip-docs # 索引名称
    mcp:
      client:
        stdio:
          servers-configuration: classpath:/json/mcp-server.json

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ai_trip?serverTimezone=UTC&useSSL=false
    username: root
    password: root
  data:
    redis:
      host: 127.0.0.1
      password: 123321
  elasticsearch:
    uris: localhost:9200
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
jwt:
  properties:
    secret-key: aitripassistant
    expired: 900000
    tokenName: token
logging:
  level:
    com.xcg.aitripassistant.mapper: debug
    org.ibatis: debug
